//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
        public string Genres { get; set; }
        public string Treiler { get; set; }
        public byte[] ImgBack { get; set; }
        public byte[] ImgFront { get; set; }
        public Nullable<double> RatingIMDb { get; set; }
        public Nullable<double> RatingKinoPoisk { get; set; }
    }
}
